apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: resolver-pipeline
spec:
  tasks:
    - name: resolver-task
      taskRef:
        resolver: git
        params:
        - name: repo
          value: private-git
        - name: org
          value: srivickynesh
        - name: revision
          value: main
        - name: pathInRepo
          value: task/resolver/resolver-task.yaml
