apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: resolver-pipeline
spec:
  tasks:
    - name: resolver-task
      taskRef:
        resolver: git
        params:
        - name: repo
          value: test-private
        - name: org
          value: openshift-pipelines
        - name: revision
          value: main
        - name: pathInRepo
          value: resolver-task.yaml
